[project]
name = "usd-convert-gsplat"
version = "0.1.15"
description = "NVIDIA 3D Gaussian Splat to USD Converter"
authors = [
    {name = "NVIDIA"},
]
license-files = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
license = {text = "Apache-2.0 AND CC-BY-4.0"}
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy==2.3.1",
]

[project.urls]
Homepage = "https://docs.omniverse.nvidia.com/kit/docs/gsplat-converter"
Documentation = "https://docs.omniverse.nvidia.com/kit/docs/gsplat-converter"

[project.optional-dependencies]
usd = [
    "usd-core>=26.3; platform_machine != 'aarch64' or platform_system != 'Linux'",
    "usd-exchange==2.3.0; platform_machine == 'aarch64' and platform_system == 'Linux'",
]

[project.scripts]
usd-convert-gsplat = "usd_convert_gsplat.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["usd_convert_gsplat"]
artifacts = [
    "usd_convert_gsplat/_version.py",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
